"""Deterministic mock LLM provider."""

from __future__ import annotations

from api.app.llm.schemas import (
    LLMGenerateRequest,
    LLMGenerateResponse,
    LLMPlatformOutput,
)


class MockLLMProvider:
    """Generate stable demo content without external API calls."""

    provider_name = "mock"

    def __init__(self, model: str = "mock-contentops-v1") -> None:
        self.model = model

    def generate_platform_content(
        self,
        request: LLMGenerateRequest,
    ) -> LLMGenerateResponse:
        """Return deterministic platform outputs for local demos and CI."""
        outputs = [
            LLMPlatformOutput(
                platform=platform,
                title=f"{request.title} | {platform}",
                body=(
                    f"{request.source_text}\n\n"
                    f"Tone: {request.tone}. Requirements: "
                    f"{request.requirements or 'standard content operations demo'}."
                ),
                hashtags=[platform, "contentops", "ai-agent"],
                summary=f"Mock {platform} adaptation for {request.title}.",
                cta="Review the generated preview before mock publishing.",
                notes="Generated by the mock provider; no external LLM was called.",
            )
            for platform in request.target_platforms
        ]

        return LLMGenerateResponse(
            platform_outputs=outputs,
            provider=self.provider_name,
            model=self.model,
            usage={},
            warnings=["mock provider used; no real LLM call was made"],
        )
